version: "2"
services:
    server:
        container_name: server
        build: ./server
        ports:
            - "8080:8080"
        links:
            - mongo

    client:
        container_name: client
        build: ./client
        ports:
            - "3000:3000"
        links:
            - server

    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./server/storage:/data/db
        ports:
            - "27017:27017"
